export const GET_ORDERS = 'api/orders';
export const CREATE_ORDER = 'api/orders';
export const GET_ALL_SALES = 'api/orders/sales';
export const GET_PURCHASES = 'api/orders/purchases';
export const FIND_ORDER = (id) => `api/orders/${id}`;
export const CREATE_PRE_ORDER = 'api/orders/pre-order';
export const GET_SALES = (id) => `api/orders/${id}/sales`;
export const ACTIVATE_MEMBERSHIP = 'api/orders/membership';
export const CREATE_HOLYMARKET_ORDER = 'api/orders/holymarket';
export const GET_FULL_DETAILS = (id) => `api/orders/${id}/all`;
export const PAY_ORDER = (id) => `api/orders/${id}/pay/stripe`;
export const GET_ORDER_FROM_ASSISTANCES = 'api/orders/assistance';
export const APPROVED_ORDER = (id) => `api/orders/${id}/approved`;
export const ADD_FILE_TO_ORDER = (id) => `api/orders/${id}/files`;
export const FIND_DISCOUNT = (id) => `api/orders/${id}/discounts`;
export const FIND_SUBSCRIPTION = (id) => `api/orders/${id}/subscriptions`;
export const FIND_ORDER_BY_REFERENCE = (id) => `api/orders/${id}/reference`;
export const INITIATE_PAYMENT = (id) => `api/orders/${id}/initiate-payment`;
export const PAY_ORDER_BY_TRANSFER = (id) => `api/orders/${id}/pay/transfer`;
export const PAY_ORDER_BY_COMMUNITY = (id) => `api/orders/${id}/pay/community`;
export const APPROVE_PAYMENT = (id) => `api/orders/payments/${id}/approved`;
export const GET_SUB_ORDERS = (reference) => `api/orders/${reference}/orders`;
export const SEND_PAYMENT_REQUEST = (id) => `api/orders/${id}/initiate-payment`;

export const GET_ORDER_SELLERS = (reference) => `api/orders/${reference}/sellers`;
export const SET_ORDER_SELLER = (reference) => `api/orders/${reference}/sellers`;
export const GET_ORDER_PRODUCT = (reference) => `api/orders/${reference}/product`;
export const CONFIGURE_ORDER_CODEV = (reference) => `api/orders/${reference}/codev`;
export const SUBSCRIBE_NEW_LINE = (reference) => `api/orders/accounts/${reference}/subscriptions`;
export const ASSIGN_DELIVERER = 'api/deliveries/parcels';