export const GET_ORDERS = 'api/orders';
export const CREATE_ORDER = 'api/orders';
export const GET_PURCHASES = 'api/orders/purchases';
export const FIND_ORDER = (id) => `api/orders/${id}`;
export const CREATE_PRE_ORDER = 'api/orders/pre-order';
export const GET_SALES = (id) => `api/orders/${id}/sales`;
export const PAY_ORDER = (id) => `api/orders/${id}/pay/stripe`;
export const APPROVED_ORDER = (id) => `api/orders/${id}/approved`;
export const ADD_FILE_TO_ORDER = (id) => `api/orders/${id}/files`;
export const FIND_DISCOUNT = (id) => `api/orders/${id}/discounts`;
export const FIND_SUBSCRIPTION = (id) => `api/orders/${id}/subscriptions`;