// Settings actions
export const DARK_MODE = 'DARK_MODE';
export const RTL_LAYOUT = 'RTL_LAYOUT';
export const BOXED_LAYOUT = 'BOXED_LAYOUT';
export const MINI_SIDEBAR = 'MINI_SIDEBAR';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const STOP_USER_TOUR = 'STOP_USER_TOUR';
export const START_USER_TOUR = 'START_USER_TOUR';
export const COLLAPSED_SIDEBAR = 'COLLAPSED_SIDEBAR';
export const SET_SIDEBAR_IMAGE = 'SET_SIDEBAR_IMAGE';
export const SEARCH_FORM_ENABLE = 'SEARCH_FORM_ENABLE';
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const TOGGLE_DARK_SIDENAV = 'TOGGLE_DARK_SIDENAV';
export const TOGGLE_SIDEBAR_IMAGE = 'TOGGLE_SIDEBAR_IMAGE';
export const CHANGE_AGENCY_LAYOUT_BG = 'CHANGE_AGENCY_LAYOUT_BG';
export const SET_PERMISSION_ALERT_BOX = 'SET_PERMISSION_ALERT_BOX'
export const SET_REQUEST_GLOBAL_LOADER = 'SET_REQUEST_GLOBAL_LOADER';

// Auth user Actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const CLEAR_AUTH_USER = 'CLEAR_AUTH_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const SET_AUTH_USER_FAILURE = 'SET_AUTH_USER_FAILURE';
export const SET_AUTH_USER_SUCCESS = 'SET_AUTH_USER_SUCCESS';

// App loader actions
export const ENABLE_APP_LOADING = 'ENABLE_APP_LOADING';
export const DISABLE_APP_LOADING = 'DISABLE_APP_LOADING';

// Cart
export const CART_CLEAR = 'CART_CLEAR';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_INIT_ITEM = 'CART_INIT_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';

export const ON_QUANTITY_CHANGE = 'ON_QUANTITY_CHANGE';
export const ON_ADD_ITEM_TO_CART = 'ON_ADD_ITEM_TO_CART';
export const ON_DELETE_ITEM_FROM_CART = 'ON_DELETE_ITEM_FROM_CART';

export const ON_SELECT_COMMUNITY = 'ON_SELECT_COMMUNITY';