/**
 * App Redux Action Types
 */
export const ENABLE_APP_LOADING = 'ENABLE_APP_LOADING';
export const DISABLE_APP_LOADING = 'DISABLE_APP_LOADING';

export const SET_REQUEST_GLOBAL_LOADER = 'SET_REQUEST_GLOBAL_LOADER';

export const SET_PERMISSION_ALERT_BOX = 'SET_PERMISSION_ALERT_BOX';

// NetworkProfile
export const NETWORK_PROFILE = 'NETWORK_PROFILE';
export const NETWORK_PROFILE_SUCCESS = 'NETWORK_PROFILE_SUCCESS';
export const NETWORK_PROFILE_FAILURE = 'NETWORK_PROFILE_FAILURE';

// NetworkProfileType
export const NETWORK_PROFILE_TYPE = 'NETWORK_PROFILE_TYPE';
export const NETWORK_PROFILE_TYPE_SUCCESS = 'NETWORK_PROFILE_TYPE_SUCCESS';
export const NETWORK_PROFILE_TYPE_FAILURE = 'NETWORK_PROFILE_TYPE_FAILURE';

// Users
export const USERS = 'USERS';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILURE = 'USERS_FAILURE';

// Branch's user
export const BRANCH_USERS = 'BRANCH_USERS';
export const BRANCH_USERS_SUCCESS = 'BRANCH_USERS_SUCCESS';
export const BRANCH_USERS_FAILURE = 'BRANCH_USERS_FAILURE';

// Catalog
export const CATALOG = 'CATALOG';
export const CATALOG_SUCCESS = 'CATALOG_SUCCESS';
export const CATALOG_FAILURE = 'CATALOG_FAILURE';

// CatalogType
export const CATALOG_TYPE = 'CATALOG_TYPE';
export const CATALOG_TYPE_SUCCESS = 'CATALOG_TYPE_SUCCESS';
export const CATALOG_TYPE_FAILURE = 'CATALOG_TYPE_FAILURE';

// CatalogProducts
export const CATALOG_PRODUCTS = 'CATALOG_PRODUCTS';
export const CATALOG_PRODUCTS_SUCCESS = 'CATALOG_PRODUCTS_SUCCESS';
export const CATALOG_PRODUCTS_FAILURE = 'CATALOG_PRODUCTS_FAILURE';

// CategoryProducts
export const CATEGORY_PRODUCTS = 'CATEGORY_PRODUCTS';
export const CATEGORY_PRODUCTS_SUCCESS = 'CATEGORY_PRODUCTS_SUCCESS';
export const CATEGORY_PRODUCTS_FAILURE = 'CATEGORY_PRODUCTS_FAILURE';

// CategoryProducts
export const PRODUCT_TYPE = 'PRODUCT_TYPE';
export const PRODUCT_TYPE_SUCCESS = 'PRODUCT_TYPE_SUCCESS';
export const PRODUCT_TYPE_FAILURE = 'PRODUCT_TYPE_FAILURE';

// Branch Product
export const BRANCH_PRODUCT = 'BRANCH_PRODUCT';
export const BRANCH_PRODUCT_SUCCESS = 'BRANCH_PRODUCT_SUCCESS';
export const BRANCH_PRODUCT_FAILURE = 'BRANCH_PRODUCT_FAILURE';

// User Profile
export const USER_PROFILE = 'USER_PROFILE';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILURE = 'USER_PROFILE_FAILURE';

// User Permissions
export const USER_PERMISSIONS = 'USER_PERMISSIONS';
export const USER_PERMISSIONS_SUCCESS = 'USER_PERMISSIONS_SUCCESS';
export const USER_PERMISSIONS_FAILURE = 'USER_PERMISSIONS_FAILURE';

// User Communities
export const USER_COMMUNITIES = 'USER_COMMUNITIES';
export const USER_COMMUNITIES_SUCCESS = 'USER_COMMUNITIES_SUCCESS';
export const USER_COMMUNITIES_FAILURE = 'USER_COMMUNITIES_FAILURE';

// User Communities admins
export const USER_COMMUNITIES_ADMIN = 'USER_COMMUNITIES_ADMIN';
export const USER_COMMUNITIES_ADMIN_SUCCESS = 'USER_COMMUNITIES_ADMIN_SUCCESS';
export const USER_COMMUNITIES_ADMIN_FAILURE = 'USER_COMMUNITIES_ADMIN_FAILURE';

// User Communities not in
export const USER_COMMUNITIES_NOT_IN = 'USER_COMMUNITIES_NOT_IN';
export const USER_COMMUNITIES_NOT_IN_SUCCESS = 'USER_COMMUNITIES_NOT_IN_SUCCESS';
export const USER_COMMUNITIES_NOT_IN_FAILURE = 'USER_COMMUNITIES_NOT_IN_FAILURE';

// Pending Invitations
export const COM_INVITATIONS_PENDING = 'COM_INVITATIONS_PENDING';
export const COM_INVITATIONS_PENDING_SUCCESS = 'COM_INVITATIONS_PENDING_SUCCESS';
export const COM_INVITATIONS_PENDING_FAILURE = 'COM_INVITATIONS_PENDING_FAILURE';

export const SET_CURRENT_COMMUNITY = 'SET_CURRENT_COMMUNITY';
export const SET_CURRENT_COMMUNITY_SUCCESS = 'SET_CURRENT_COMMUNITY_SUCCESS';
export const SET_CURRENT_COMMUNITY_FAILURE = 'SET_CURRENT_COMMUNITY_FAILURE';

export const PACKAGES = 'PACKAGES';
export const PACKAGES_SUCCESS = 'PACKAGES_SUCCESS';
export const PACKAGES_FAILURE = 'PACKAGES_FAILURE';

export const COMMERCIAL_OPERATION_TYPE = 'COMMERCIAL_OPERATION_TYPE';
export const COMMERCIAL_OPERATION_TYPE_SUCCESS = 'COMMERCIAL_OPERATION_TYPE_SUCCESS';
export const COMMERCIAL_OPERATION_TYPE_FAILURE = 'COMMERCIAL_OPERATION_TYPE_FAILURE';

export const COMMERCIAL_OPERATION = 'COMMERCIAL_OPERATION';
export const COMMERCIAL_OPERATION_SUCCESS = 'COMMERCIAL_OPERATION_SUCCESS';
export const COMMERCIAL_OPERATION_FAILURE = 'COMMERCIAL_OPERATION_FAILURE';

export const COMMERCIAL_OFFER = 'COMMERCIAL_OFFER';
export const COMMERCIAL_OFFER_SUCCESS = 'COMMERCIAL_OFFER_SUCCESS';
export const COMMERCIAL_OFFER_FAILURE = 'COMMERCIAL_OFFER_FAILURE';

export const PRODUCT = 'PRODUCT';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

export const MANDATE_TYPE = 'MANDATE_TYPE';
export const MANDATE_TYPE_SUCCESS = 'MANDATE_TYPE_SUCCESS';
export const MANDATE_TYPE_FAILURE = 'MANDATE_TYPE_FAILURE';

export const MANDATE_MODEL = 'MANDATE_MODEL';
export const MANDATE_MODEL_SUCCESS = 'MANDATE_MODEL_SUCCESS';
export const MANDATE_MODEL_FAILURE = 'MANDATE_MODEL_FAILURE';

export const MANDATE = 'MANDATE';
export const MANDATE_SUCCESS = 'MANDATE_SUCCESS';
export const MANDATE_FAILURE = 'MANDATE_FAILURE';

export const NOTIFICATION_MODEL = 'NOTIFICATION_MODEL';
export const NOTIFICATION_MODEL_SUCCESS = 'NOTIFICATION_MODEL_SUCCESS';
export const NOTIFICATION_MODEL_FAILURE = 'NOTIFICATION_MODEL_FAILURE';

export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const NOTIFICATION_SERVICE_SUCCESS = 'NOTIFICATION_SERVICE_SUCCESS';
export const NOTIFICATION_SERVICE_FAILURE = 'NOTIFICATION_SERVICE_FAILURE';

export const NOTIFICATION = 'NOTIFICATION';
export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAILURE = 'NOTIFICATION_FAILURE';

export const USERS_ACCOUNTS = 'USERS_ACCOUNTS';
export const USERS_ACCOUNTS_SUCCESS = 'USERS_ACCOUNTS_SUCCESS';
export const USERS_ACCOUNTS_FAILURE = 'USERS_ACCOUNTS_FAILURE';

// Cart
export const CART_CLEAR = 'CART_CLEAR';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';

export const SAMPLE_BRANCHES = 'SAMPLE_BRANCHES';
export const SAMPLE_BRANCHES_SUCCESS = 'SAMPLE_BRANCHES_SUCCESS';
export const SAMPLE_BRANCHES_FAILURE = 'SAMPLE_BRANCHES_FAILURE';

export const PROJECT_WORKS = 'PROJECT_WORKS';
export const PROJECT_WORKS_SUCCESS = 'PROJECT_WORKS_SUCCESS';
export const PROJECT_WORKS_FAILURE = 'PROJECT_WORKS_FAILURE';

export const PROJECTS = 'PROJECTS';
export const PROJECTS_SUCCESS = 'PROJECTS_SUCCESS';
export const PROJECTS_FAILURE = 'PROJECTS_FAILURE';

export const PROJECT_STANDARD = 'PROJECT_STANDARD';
export const PROJECT_STANDARD_SUCCESS = 'PROJECT_STANDARD_SUCCESS';
export const PROJECT_STANDARD_FAILURE = 'PROJECT_STANDARD_FAILURE';

export const PROJECT_STANDARD_PRESENTATION = 'PROJECT_STANDARD_PRESENTATION';
export const PROJECT_STANDARD_PRESENTATION_SUCCESS = 'PROJECT_STANDARD_PRESENTATION_SUCCESS';
export const PROJECT_STANDARD_PRESENTATION_FAILURE = 'PROJECT_STANDARD_PRESENTATION_FAILURE';

export const INITIALISATION_IDEA = 'INITIALISATION_IDEA';
export const INITIALISATION_IDEA_SUCCESS = 'INITIALISATION_IDEA_SUCCESS';
export const INITIALISATION_IDEA_FAILURE = 'INITIALISATION_IDEA_FAILURE';

export const INITIALISATION_PROJECTS_CALL = 'INITIALISATION_PROJECTS_CALL';
export const INITIALISATION_PROJECTS_CALL_SUCCESS = 'INITIALISATION_PROJECTS_CALL_SUCCESS';
export const INITIALISATION_PROJECTS_CALL_FAILURE = 'INITIALISATION_PROJECTS_CALL_FAILURE';

export const INITIALISATION_PROGRAM = 'INITIALISATION_PROGRAM';
export const INITIALISATION_PROGRAM_SUCCESS = 'INITIALISATION_PROGRAM_SUCCESS';
export const INITIALISATION_PROGRAM_FAILURE = 'INITIALISATION_PROGRAM_FAILURE';

export const FOLDERS = 'FOLDERS';
export const FOLDERS_SUCCESS = 'FOLDERS_SUCCESS';
export const FOLDERS_FAILURE = 'FOLDERS_FAILURE';


export const COLLAPSED_SIDEBAR = 'COLLAPSED_SIDEBAR';
export const DARK_MODE = 'DARK_MODE';
export const BOXED_LAYOUT = 'BOXED_LAYOUT';
export const RTL_LAYOUT = 'RTL_LAYOUT';
export const MINI_SIDEBAR = 'MINI_SIDEBAR';
export const SEARCH_FORM_ENABLE = 'SEARCH_FORM_ENABLE';
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const TOGGLE_SIDEBAR_IMAGE = 'TOGGLE_SIDEBAR_IMAGE';
export const SET_SIDEBAR_IMAGE = 'SET_SIDEBAR_IMAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const START_USER_TOUR = 'START_USER_TOUR';
export const STOP_USER_TOUR = 'STOP_USER_TOUR';
export const TOGGLE_DARK_SIDENAV = 'TOGGLE_DARK_SIDENAV';
// Chat App Actions
export const CHAT_WITH_SELECTED_USER = 'CHAT_WITH_SELECTED_USER';
export const SEND_MESSAGE_TO_USER = 'SEND_MESSAGE_TO_USER';
export const UPDATE_USERS_SEARCH = 'UPDATE_USERS_SEARCH';
export const SEARCH_USERS = 'SEARCH_USERS';
export const GET_RECENT_CHAT_USERS = 'GET_RECENT_CHAT_USERS';
// Agency Sidebar
export const AGENCY_TOGGLE_MENU = 'AGENCY_TOGGLE_MENU';
export const CHANGE_AGENCY_LAYOUT_BG = 'CHANGE_AGENCY_LAYOUT_BG';
// Mail App
export const GET_EMAILS = 'GET_EMAILS';
export const GET_EMAIL_SUCCESS = 'GET_EMAIL_SUCCESS';
export const GET_EMAIL_FAILURE = 'GET_EMAIL_FAILURE';
export const SET_EMAIL_AS_STAR = 'SET_EMAIL_AS_STAR';
export const READ_EMAIL = 'READ_EMAIL';
export const HIDE_LOADING_INDICATOR = 'HIDE_LOADING_INDICATOR';
export const FETCH_EMAILS = 'FETCH_EMAILS';
export const ON_SELECT_EMAIL = 'ON_SELECT_EMAIL';
export const UPDATE_EMAIL_SEARCH = 'UPDATE_EMAIL_SEARCH';
export const SEARCH_EMAIL = 'SEARCH_EMAIL';
export const ON_DELETE_MAIL = 'ON_DELETE_MAIL';
export const ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING = 'ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING';
export const GET_SENT_EMAILS = 'GET_SENT_EMAILS';
export const GET_INBOX = 'GET_INBOX';
export const GET_DRAFTS_EMAILS = 'GET_DRAFTS_EMAILS';
export const GET_SPAM_EMAILS = 'GET_SPAM_EMAILS';
export const GET_TRASH_EMAILS = 'GET_TRASH_EMAILS';
export const ON_EMAIL_MOVE_TO_FOLDER = 'ON_EMAIL_MOVE_TO_FOLDER';
export const SELECT_ALL_EMAILS = 'SELECT_ALL_EMAILS';
export const UNSELECT_ALL_EMAILS = 'UNSELECT_ALL_EMAILS';
export const ON_SEND_EMAIL = 'ON_SEND_EMAIL';
export const EMAIL_SENT_SUCCESSFULLY = 'EMAIL_SENT_SUCCESSFULLY';
export const FILTER_EMAILS_WITH_LABELS = 'FILTER_EMAILS_WITH_LABELS';
export const ADD_LABELS_INTO_EMAILS = 'ADD_LABELS_INTO_EMAILS';
// sidebar
export const TOGGLE_MENU = 'TOGGLE_MENU';
// ToDo App
export const GET_TODOS = 'GET_TODOS';
export const FETCH_TODOS = 'FETCH_TODOS';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const ON_SELECT_TODO = 'ON_SELECT_TODO';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';
export const ON_BACK_TO_TODOS = 'ON_BACK_TO_TODOS';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
export const MARK_AS_STAR_TODO = 'MARK_AS_STAR_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const ADD_LABELS_INTO_THE_TASK = 'ADD_LABELS_INTO_THE_TASK';
export const GET_ALL_TODO = 'GET_ALL_TODO';
export const GET_COMPLETED_TODOS = 'GET_COMPLETED_TODOS';
export const GET_DELETED_TODOS = 'GET_DELETED_TODOS';
export const GET_STARRED_TODOS = 'GET_STARRED_TODOS';
export const GET_FILTER_TODOS = 'GET_FILTER_TODOS';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const COMPLETE_TASK = 'COMPLETE_TASK';
export const UPDATE_TASK_TITLE = 'UPDATE_TASK_TITLE';
export const UPDATE_TASK_DESCRIPTION = 'UPDATE_TASK_DESCRIPTION';
export const CHANGE_TASK_ASSIGNER = 'CHANGE_TASK_ASSIGNER';
export const ON_CHECK_BOX_TOGGLE_TODO_ITEM = 'ON_CHECK_BOX_TOGGLE_TODO_ITEM';
export const SELECT_ALL_TODO = 'SELECT_ALL_TODO';
export const GET_UNSELECTED_ALL_TODO = 'GET_UNSELECTED_ALL_TODO';
export const SELECT_STARRED_TODO = 'SELECT_STARRED_TODO';
export const SELECT_UNSTARRED_TODO = 'SELECT_UNSTARRED_TODO';
export const ON_LABEL_SELECT = 'ON_LABEL_SELECT';
export const ON_LABEL_MENU_ITEM_SELECT = 'ON_LABEL_MENU_ITEM_SELECT';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const SEARCH_TODO = 'SEARCH_TODO';

// Auth user Actions
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_USER_SUCCESS = 'SET_AUTH_USER_SUCCESS';
export const SET_AUTH_USER_FAILURE = 'SET_AUTH_USER_FAILURE';
export const CLEAR_AUTH_USER = 'CLEAR_AUTH_USER';

// Auth Actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';


// Feedbacks
export const GET_FEEDBACKS = 'GET_FEEDBACKS';
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS';
export const GET_ALL_FEEDBACKS = 'GET_ALL_FEEDBACKS';
export const ON_CHANGE_FEEDBACK_PAGE_TABS = 'ON_CHANGE_FEEDBACK_PAGE_TABS';
export const MAKE_FAVORITE_FEEDBACK = 'MAKE_FAVORITE_FEEDBACK';
export const ON_DELETE_FEEDBACK = 'ON_DELETE_FEEDBACK';
export const VIEW_FEEDBACK_DETAILS = 'VIEW_FEEDBACK_DETAILS';
export const ADD_NEW_FEEDBACK = 'ADD_NEW_FEEDBACK';
export const SHOW_FEEDBACK_LOADING_INDICATOR = 'SHOW_FEEDBACK_LOADING_INDICATOR';
export const HIDE_FEEDBACK_LOADING_INDICATOR = 'HIDE_FEEDBACK_LOADING_INDICATOR';
export const NAVIGATE_TO_BACK = 'NAVIGATE_TO_BACK';
export const REPLY_FEEDBACK = 'REPLY_FEEDBACK';
export const SEND_REPLY = 'SEND_REPLY';
export const UPDATE_SEARCH_IDEA = 'UPDATE_SEARCH_IDEA';
export const ON_SEARCH_IDEA = 'ON_SEARCH_IDEA';
export const ON_COMMENT_FEEDBACK = 'ON_COMMENT_FEEDBACK';
// ecommerce
export const ON_DELETE_ITEM_FROM_CART = 'ON_DELETE_ITEM_FROM_CART';
export const ON_QUANTITY_CHANGE = 'ON_QUANTITY_CHANGE';
export const ON_ADD_ITEM_TO_CART = 'ON_ADD_ITEM_TO_CART';
//crm
export const ADD_NEW_CLIENT = 'ADD_NEW_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';

// System objects
export const SYS_PRODUCT_NATURE = 'SYS_PRODUCT_NATURE';
export const SYS_PRODUCT_NATURE_SUCCESS = 'SYS_PRODUCT_NATURE_SUCCESS';
export const SYS_PRODUCT_NATURE_FAILURE = 'SYS_PRODUCT_NATURE_FAILURE';

export const SYS_TIME_UNIT = 'SYS_TIME_UNIT';
export const SYS_TIME_UNIT_SUCCESS = 'SYS_TIME_UNIT_SUCCESS';
export const SYS_TIME_UNIT_FAILURE = 'SYS_PRODUCT_NATURE_FAILURE';


export const COMMUNIY_INVITATION_ADD = "COMMUNIY_INVITATION_ADD";
export const COMMUNIY_INVITATION_ADD_CHANGE_ROLE_PROJECT = "COMMUNIY_INVITATION_ADD_CHANGE_ROLE_PROJECT";

// Post Projects
export const POST_PROJECT_GET_ALL = "POST_PROJECT_GETALL";


export const COMMUNITY_SPACE_GET_STATUS = "COMMUNITY_SPACE_GET_STATUS";
export const COMMUNITY_SPACE_SET_STATUS = "COMMUNITY_SPACE_SET_STATUS";
export const COMMUNITY_SPACE_SET_VALUE = "COMMUNITY_SPACE_SET_VALUE";
export const COMMUNITY_SPACE_SET_ADMINS = "COMMUNITY_SPACE_SET_ADMINS";

export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_CURRENCIES_SUCCESS = 'SET_CURRENCIES_SUCCESS';
export const SET_CURRENCIES_FAILURE = 'SET_CURRENCIES_FAILURE';